print("Today I have worked on list comprehensions in Python towards my interview - 13/02/25")
print("Further work completed on list comprehensions in Python towards my interview - 14/02/25")
print("Finished all exercises on list comprehensions, dictionary comprehensions and set comprehensions; then completed sets and tuple exclusive exercises")
print("Also reviewed core concepts such as loops, functions and variables")
print("I completed a mixture of logic problems and practice questions in Python; these short problems covered a range of topics including loops, comprehensions, and string manipulation - 16/02/25")
print("More logic problems and practice questions in Python; learned how to work with the ord() and char() functions to parse back and forth between corresponding ASCII values - 17/02/25")
print("More logic problems; recursive functions as well as abstract list and dictionary manipulations - 17/02/25")
print("Still working - learning about lambda functions 09/03/25")
print("Xanax Damage")
print("System Design Studies :)")
print("Lamba Handlers in AWS")
print("RIP to Keed")