print("Today I have worked on list comprehensions in Python towards my interview - 13/02/25")
print("Further work completed on list comprehensions in Python towards my interview - 14/02/25")
print("Finished all exercises on list comprehensions, dictionary comprehensions and set comprehensions; then completed sets and tuple exclusive exercises")
print("Also reviewed core concepts such as loops, functions and variables")
print("I completed a mixture of logic problems and practice questions in Python; these short problems covered a range of topics including loops, comprehensions, and string manipulation - 16/02/25")
print("More logic problems and practice questions in Python; learned how to work with the ord() and char() functions to parse back and forth between corresponding ASCII values - 17/02/25")
print("More logic problems; recursive functions as well as abstract list and dictionary manipulations - 17/02/25")
print("Still working - learning about lambda functions 09/03/25")
print("Xanax Damage")
print("System Design Studies")
print("Lamba Handlers in AWS")
print("RIP to Keed")
print("Attended an interview final round - fingers crossed!")
print("Attended initial interview - fingers crossed")
print("Exams done!!!")
print("Interview prep done - fingers crossed for tomorrow!")
print("Final round interview done")
print("Verbal contract agreed - onto referees!!!")
print("Collecting references - fingers crossed!!!")
print("References secured - almost there!")
print("Nothing to report; working on Google Co-Labs platform")
print("All Shounen")
print("All good - completed TA training today :)")
print("Moved my brother to Thailand!!!")
print("Prep work for new TA role begins today :)")
print("Day done - mixed bag of students; needs more work")
print("Day done - content was easier so students did better@k")
print("Saturday rest day - back to it tomorrow!")